$(document).ready(function(){$("#slide-nav.navbar-inverse").after($('<div class="inverse" id="navbar-height-col"></div>'));$("#slide-nav.navbar-default").after($('<div id="navbar-height-col"></div>'));$("#slide-nav").on("click",".navbar-toggle",function(a){a=$(this).hasClass("slide-active");$("#slidemenu").stop().animate({left:a?"-100%":"0px"});$("#navbar-height-col").stop().animate({left:a?"-80%":"0px"});$("#page-content").stop().animate({left:a?"0px":"80%"});$(".navbar-header").stop().animate({left:a?
"0px":"80%"});$(this).toggleClass("slide-active",!a);$("#slidemenu").toggleClass("slide-active");$(".navbar-collapse ul li a").click(function(){$(".navbar-toggle:visible").click()});$("#page-content, .navbar, body, .navbar-header").toggleClass("slide-active")});$(window).on("resize",function(){767<$(window).width()&&$(".navbar-toggle").is(":hidden")&&$("#slidemenu, #page-content, body, .navbar, .navbar-header").removeClass("slide-active")})});var Id="",objTyp="";
function popSearchLayers(){$("#loading_bg, #loading").show();document.body.style.cursor="wait";document.getElementById("searchLayer").innerHTML="";document.getElementById("searchObject").innerHTML="";arr_layer.sort();for(var a=0;a<arr_layer.length;a++)if("PN"==arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"))||"CP"==arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"))){var b=document.createElement("option");b.value=arr_layer[a].substring(arr_layer[a].indexOf("~")+1,
arr_layer[a].indexOf("|"))+"^"+arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"));b.innerHTML=arr_layer[a].substring(0,arr_layer[a].indexOf("~"));document.getElementById("searchLayer").appendChild(b)}""==document.getElementById("searchLayer").value?(alert("No Layer selected for Search!!!"),$("#loading_bg, #loading").hide(),document.body.style.cursor="default"):popSearchObjectNames()}
function popSearchObjectNames(){$("#loading_bg, #loading").show();document.body.style.cursor="wait";document.getElementById("searchObject").innerHTML="";Id=document.getElementById("searchLayer").options[document.getElementById("searchLayer").selectedIndex].value;objTyp=Id.substring(Id.indexOf("^")+1,Id.length);var a=Id.substring(0,Id.indexOf("^")),b;b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){if("N/A"==
b.responseText)alert("No Object found for the selected Layer!!!");else for(var a=eval("("+b.responseText+")"),c=0;c<a.length;c++){var d=document.createElement("option");d.value=a[c][0];d.innerHTML=a[c][1];document.getElementById("searchObject").appendChild(d)}$("#loading_bg, #loading").hide();document.body.style.cursor="default"}};b.open("GET","search.objNames?map_rltd="+map_rltd+"&obj_srch_rltd="+a+"&obj_type="+objTyp+"&map_id="+map_id,!0);b.send()}
function searchObject(){$("#loading_bg, #loading").show();document.body.style.cursor="wait";clearHatchedObjects();var a=document.getElementById("searchObject").value;document.getElementById("searchLayer");if("PN"==objTyp)for(var b=0;b<markers.length;b++){if(markers[b].id==a){var f=new google.maps.Marker({position:markers[b].position,map:map});markers.push(f);f.type="SrchObj"}}else if("CP"==objTyp)for(b=0;b<closedPolyMulti.length;b++)closedPolyMulti[b].id==a&&(f=new google.maps.Polygon({path:closedPolyMulti[b].path,
strokeOpacity:.8,strokeWeight:"2",fillColor:"#8B0000",fillOpacity:.35}),closedPolyMulti.push(f),f.type="SrchPolygonObj",f.setMap(map));$("#loading_bg, #loading").hide();document.body.style.cursor="default"};function prepLayersTab(a){$("#loading_bg, #loading").show();document.body.style.cursor="wait";var b=null;document.getElementById("tableLayer").innerHTML="";var f=new XMLHttpRequest;f.open("GET","lyr.info?map_id="+a,!0);f.send();f.onreadystatechange=function(){if(4==f.readyState&&200==f.status&&"N/A"!=f.responseText){for(var c=eval("("+f.responseText+")"),d="",e=0;e<c.length;e++)"GROUP"==c[e][1]?(5<d.length&&(d+="</table></div>"),d=d+"<div style='font-size: 13px; background-color: #4171B9; color: #ffffff; padding:4px; margin: 2px;'>"+
c[e][0]+"</div><div><table>"):(b="http://74.50.58.66/systems/od_creche/icons/"+c[e][1]+".png","ST"==map_rltd?"ST"==c[e][1]?(d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px;  top: -6px;'><input type='checkbox' checked disabled id='"+c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+"</td>",getLayerData(map_rltd,c[e][1],c[e][2],a)):"DT"==c[e][1]?(d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px;  top: -6px;'><input type='checkbox' checked id='"+
c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+"</td>",getLayerData(map_rltd,c[e][1],c[e][2],a),arr_layer.push(c[e][0]+"~"+c[e][1]+"|CP#1")):d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px; top: -6px;'><input type='checkbox' id='"+c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+
"</td>":"DT"==c[e][1]?(d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px;  top: -6px;'><input type='checkbox' checked disabled id='"+c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+"</td>",getLayerData(map_rltd,c[e][1],c[e][2],a)):"SD"==c[e][1]?(d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px;  top: -6px;'><input type='checkbox' checked id='"+
c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+"</td>",getLayerData(map_rltd,c[e][1],c[e][2],a),arr_layer.push(c[e][0]+"~"+c[e][1]+"|CP#1")):d+="<tr><td class='checkbox_lbl' style='font-size: 11px; position: relative; left: -20px; top: -6px;'><input type='checkbox' id='"+c[e][1]+"' value='"+c[e][1]+"' onclick='displayLayers(this, &#39;"+c[e][2]+"&#39;, &#39;"+c[e][0]+"&#39;, &#39;"+c[e][3]+"&#39;)'> "+c[e][0]+
"</td>",d+="<td class='map_icon' style='width: 12px;'><img src='"+b+"'></td></tr>");5<d.length&&(d+="</table></div>");document.getElementById("tableLayer").innerHTML=d;$("#tableLayer").accordion("refresh");$("#tableLayer").accordion({active:0});$("#loading_bg, #loading").hide();document.body.style.cursor="default"}}}
function displayLayers(a,b,f,c){if(a.checked)getLayerData(map_rltd,a.value,b,map_id),arr_layer.push(f+"~"+a.value+"|"+b+"#"+c);else{for(var d=0;d<arr_layer.length;d++)arr_layer[d]==f+"~"+a.value+"|"+b+"#"+c&&arr_layer.splice(d,1);if("PN"==b)for(d=0;d<markers.length;d++)markers[d].type==a.value&&markers[d].setVisible(!1);else if("OP"==b)for(d=0;d<polyLinePathMulti.length;d++)polyLinePathMulti[d].type==a.value&&polyLinePathMulti[d].setVisible(!1);else if("CP"==b)for(d=0;d<closedPolyMulti.length;d++)closedPolyMulti[d].type==
a.value&&closedPolyMulti[d].setVisible(!1)}}
function getLayerData(a,b,f,c){$("#loading_bg, #loading").show();document.body.style.cursor="wait";var d;d=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");d.onreadystatechange=function(){if(4==d.readyState&&200==d.status)if("N/A"==d.responseText)alert("No Object for the Layer!!!"),$("#loading_bg, #loading").hide(),document.body.style.cursor="default";else{var a=d.responseText;"PN"==f?setMarkers(a,b):"OP"==f?getPolyLines(a,b):"CP"==f&&getClosedPoly(a,b)}};d.open("GET",
"lyr.popData?mapRltd="+a+"&objRltd="+b+"&obj_type="+f+"&mapId="+c,!0);d.send()}
function setMarkers(a,b){a=eval("("+a+")");for(var f="http://74.50.58.66/systems/od_creche/icons/"+b+".png",c=0;c<a.length;c++){var d=a[c],d=new google.maps.Marker({position:{lat:parseFloat(d[1]),lng:parseFloat(d[2])},map:map,icon:f,title:d[0],id:d[3]}),e=new google.maps.InfoWindow;markers.push(d);d.type=b;google.maps.event.addListener(d,"click",function(a,c){var d='<div id="infoWindow"><img id="bodyContent" src="img.Details?Id='+a.id+"&LId="+b+"&MapId="+map_id+'"><p>'+a.title+"</p></div>";return function(){e.setContent(d);
e.open(map,a)}}(d,c))}$("#loading_bg, #loading").hide();document.body.style.cursor="default"}
function getPolyLines(a,b){function f(a,b,c){var d=new google.maps.InfoWindow;google.maps.event.addListener(a,"click",function(a){d.setContent(c);d.setPosition(a.latLng);d.open(map)})}var c=null,d=null;if("FLPL"==b)c="#B97A57",d="3";else if("LSPL"==b)c="#AA0000",d="3";else if("MSPL"==b)c="#3A45CB",d="3";else if("NH"==b)c="#FFC345",d="4";else if("SH"==b)c="#FFFB8A",d="4";else if("RL"==b)var c="#FF0000",d="2",e={path:"M 0,1 0,1",strokeOpacity:1,scale:4};for(var k=a.split("~"),m=0;m<k.length;m++){a=
eval("("+k[m]+")");for(var l="",g=0;g<a.length;g++)var h=a[g],l=l+(parseFloat(h[1]/1E7)+","+parseFloat(h[2]/1E7)+","+h[0]+","+h[3]+"|");l=l.substring(0,l.length-1);h=l.split("|");l=[];for(g=0;g<h.length;g++){var n=new google.maps.LatLng(parseFloat(h[g].split(",")[0]),parseFloat(h[g].split(",")[1]));l.push(n);var n=h[g].split(",")[2],p=h[g].split(",")[3]}g="";g="RL"==b?new google.maps.Polyline({title:n,id:p,path:l,strokeColor:c,strokeOpacity:1,strokeWeight:d,icons:[{icon:e,offset:"0",repeat:"10px"}]}):
new google.maps.Polyline({title:n,id:p,path:l,strokeColor:c,strokeOpacity:1,strokeWeight:d});polyLinePathMulti.push(g);g.path=l;g.type=b;f(g,g.title,'<div id="infoWindow"><img id="bodyContent" src="img.Details?Id='+g.id+"&LId="+b+"&MapId="+map_id+'"><p>'+g.title+"</p></div>");g.setMap(map);$("#loading_bg, #loading").hide();document.body.style.cursor="default"}}
function getClosedPoly(a,b){function f(a,b,c){var d=new google.maps.InfoWindow;google.maps.event.addListener(a,"mouseover",function(a){d.setContent(c);d.setPosition(a.latLng);d.open(map)});google.maps.event.addListener(a,"mouseout",function(){d.close()})}var c=null,d=null,e=null,k=null;"ST"==b?(c="#000000",d="2",e="1",k="0.1"):"DT"==b?(c="#0040FF",d="2",e="1",k="0.1"):"SD"==b?(c="#00CC00",d="1",e="0.5",k="0.1"):"UB"==b?(c="#FFBB77",d="1",e="0.5",k="0.7"):"OTH"==b?(c="#7DFF7D",d="2",e="1",k="0.1"):
"VL"==b?(c="#FF8080",d="1",e="0.5",k="0.1"):"RV"==b&&(c="#A5BFDD",d="3");for(var m=a.split("~"),l=0;l<m.length;l++){a=eval("("+m[l]+")");for(var g="",h=0;h<a.length;h++)var n=a[h],g=g+(parseFloat(n[1]/1E7)+","+parseFloat(n[2]/1E7)+","+n[0]+","+n[3]+"|");g=g.substring(0,g.length-1);g=g.split("|");n=[];for(h=0;h<g.length;h++){var p=new google.maps.LatLng(parseFloat(g[h].split(",")[0]),parseFloat(g[h].split(",")[1]));n.push(p);var p=g[h].split(",")[2],q=g[h].split(",")[3]}closedPolyPath="UB"==b?new google.maps.Polygon({clickable:!0,
title:p,id:q,path:n,strokeOpacity:e,strokeWeight:d,strokeColor:c,fillColor:"#ffda6b",fillOpacity:k}):new google.maps.Polygon({clickable:!0,title:p,id:q,path:n,strokeOpacity:e,strokeWeight:d,strokeColor:c,fillColor:"#FFFFCC",fillOpacity:k});closedPolyMulti.push(closedPolyPath);closedPolyPath.path=n;closedPolyPath.type=b;strImage=document.createElement("div");strImage.style.width="auto";strImage.style.height="auto";strImage.style.top="0px";strImage.style.left="0px";strImage.style.background="white";
strImage.style.fontFamily="Trebuchet MS";strImage.style.textAlign="center";strImage.style.overflow="hidden";strImage.innerHTML=closedPolyPath.title;"ST"!=b&&f(closedPolyPath,closedPolyPath.title,strImage);closedPolyPath.setMap(map);$("#loading_bg, #loading").hide();document.body.style.cursor="default"}};var pnt_arr=[];
function populateBufferLayers(){document.getElementById("bufferLayer").innerHTML="";arr_layer.sort();for(var a=0;a<arr_layer.length;a++)if("PN"==arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"))){var b=document.createElement("option");b.value=arr_layer[a].substring(arr_layer[a].indexOf("~")+1,arr_layer[a].indexOf("|"))+"^"+arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"));b.innerHTML=arr_layer[a].substring(0,arr_layer[a].indexOf("~"));document.getElementById("bufferLayer").appendChild(b)}}
function drawBufferCircle(){removeCircle();var a=null;if(0==arr_layer.length)alert("Please select a valid layer first!!!");else{var b=document.getElementById("bufferLayer").options[document.getElementById("bufferLayer").selectedIndex].value,a=b.substring(0,b.indexOf("^")),b=document.getElementById("bufferRadius").value,f=document.getElementById("bufferDrawCol").value,f="#"+f.substring(1,f.length);if(""==b||"0"==b)alert("Please give a valid radius!!!");else{for(var c=0;c<markers.length;c++)if(markers[c].type==
a){var d=new google.maps.Marker({position:markers[c].position,icon:"http://74.50.58.66/systems/isgp/Red.png",map:map});markers.push(d);d.type="BufObj";pnt_arr.push(d.getPosition())}for(c=0;c<pnt_arr.length;c++)a=new google.maps.Circle({strokeColor:"#FF0000",strokeOpacity:.8,strokeWeight:2,fillColor:f,fillOpacity:.35,map:map,center:pnt_arr[c],radius:parseFloat(b),visible:!0}),circleMulti.push(a),a.type="BufPolygonObj"}}}
function removeCircle(){for(i=0;i<circleMulti.length;i++)"BufPolygonObj"==circleMulti[i].type&&circleMulti[i].setOptions({fillOpacity:0,strokeOpacity:0,fillColor:"",visible:!1})};var queryGroups=null,queryIndicators=null,booQueryPeriod=!1;
function popQueryLayers(){document.getElementById("queryLayer").innerHTML="";arr_layer.sort();for(var a=0;a<arr_layer.length;a++)if("1"==arr_layer[a].substring(arr_layer[a].indexOf("#")+1,arr_layer[a].length)){var b=document.createElement("option");b.value=arr_layer[a].substring(arr_layer[a].indexOf("~")+1,arr_layer[a].indexOf("|"))+"^"+arr_layer[a].substring(arr_layer[a].indexOf("|")+1,arr_layer[a].indexOf("#"));b.innerHTML=arr_layer[a].substring(0,arr_layer[a].indexOf("~"));document.getElementById("queryLayer").appendChild(b)}popQueryGroup()}
function popQueryGroup(){document.body.style.cursor="wait";if(""!=document.getElementById("queryLayer").options[document.getElementById("queryLayer").selectedIndex].value){queryGroups=[];document.getElementById("queryGroup").innerHTML="";booQueryPeriod=!1;document.getElementById("queryTabPeriod").style.visibility="collapse";document.getElementById("queryPeriod").innerHTML="";document.getElementById("queryCategory").innerHTML="";document.getElementById("queryIndicator").innerHTML="";document.getElementById("queryDataRange").innerHTML=
"";document.getElementById("queryDataSource").innerHTML="";var a=document.getElementById("queryDataOper").innerHTML="",a="",a=document.getElementById("queryLayer").options[document.getElementById("queryLayer").selectedIndex].value,a=a.substring(0,a.indexOf("^")),b=new XMLHttpRequest;b.open("GET","qry.grps?Id="+a,!0);b.send();b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){if("N/A"==b.responseText)alert("No Group Found For Query!!!");else{for(var a=eval("("+b.responseText+")"),c=
0;c<a.length;c++){queryGroups.push([a[c][0],a[c][2],a[c][3]]);var d=document.createElement("option");d.value=a[c][0];d.innerHTML=a[c][1];document.getElementById("queryGroup").appendChild(d)}popQueryCategory()}document.body.style.cursor="default"}}}}
function displayDataSrouce(){for(var a=document.getElementById("queryGroup").options[document.getElementById("queryGroup").selectedIndex].value,b=0;b<queryGroups.length;b++)if(queryGroups[b][0]==a){document.getElementById("queryDataSource").innerHTML="Data Source : "+queryGroups[b][1];break}}
function popQueryCategory(){document.body.style.cursor="wait";if(""!=document.getElementById("queryGroup").options[document.getElementById("queryGroup").selectedIndex].value){displayDataSrouce();booQueryPeriod=!1;document.getElementById("queryTabPeriod").style.visibility="collapse";document.getElementById("queryPeriod").innerHTML="";document.getElementById("queryCategory").innerHTML="";document.getElementById("queryIndicator").innerHTML="";document.getElementById("queryDataRange").innerHTML="";document.getElementById("queryDataOper").innerHTML=
"";var a=new XMLHttpRequest;a.open("GET","qry.catg?Id="+document.getElementById("queryGroup").options[document.getElementById("queryGroup").selectedIndex].value,!0);a.send();a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){if("N/A"==a.responseText)alert("No Category Found For Query!!!");else{for(var b=eval("("+a.responseText+")"),f=0;f<b.length;f++){var c=document.createElement("option");c.value=b[f][0];c.innerHTML=b[f][1];document.getElementById("queryCategory").appendChild(c)}popQueryPeriods()}document.body.style.cursor=
"default"}}}}
function popQueryPeriods(){document.body.style.cursor="wait";document.getElementById("queryPeriod").innerHTML="";for(var a=document.getElementById("queryGroup").options[document.getElementById("queryGroup").selectedIndex].value,b=0;b<queryGroups.length;b++)if(queryGroups[b][0]==a&&"1"==queryGroups[b][2]){booQueryPeriod=!0;document.getElementById("queryTabPeriod").style.visibility="visible";var f=new XMLHttpRequest;f.open("GET","qry.prds?map_id="+map_id+"&Id="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value,!0);
f.send();f.onreadystatechange=function(){if(4==f.readyState&&200==f.status){if("N/A"==f.responseText)alert("No Period Found For Query!!!");else{for(var a=eval("("+f.responseText+")"),b=0;b<a.length;b++){var e=document.createElement("option");e.value=a[b][0];e.innerHTML=a[b][0];document.getElementById("queryPeriod").appendChild(e)}popQueryIndicator()}document.body.style.cursor="default"}}}booQueryPeriod||popQueryIndicator()}
function popQueryIndicator(){document.body.style.cursor="wait";if(""!=document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value){queryIndicators=[];document.getElementById("queryIndicator").innerHTML="";document.getElementById("queryDataRange").innerHTML="";document.getElementById("queryDataOper").innerHTML="";var a=new XMLHttpRequest;a.open("GET","qry.ind?Id="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value,
!0);a.send();a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){if("N/A"==a.responseText)alert("No Indicator Found For Query!!!");else{for(var b=eval("("+a.responseText+")"),f=0;f<b.length;f++){queryIndicators.push([b[f][0],b[f][1],b[f][2],b[f][3]]);var c=document.createElement("option");c.value=b[f][0];c.innerHTML=b[f][1];document.getElementById("queryIndicator").appendChild(c)}popQueryRange()}document.body.style.cursor="default"}}}}
function popQueryRange(){document.body.style.cursor="wait";if(""!=document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value){document.getElementById("queryDataRange").innerHTML="";document.getElementById("queryDataOper").innerHTML="";for(var a=document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value,b=0;b<queryIndicators.length;b++)if(queryIndicators[b][0]==a){document.getElementById("queryIndiType").value=
queryIndicators[b][2];document.getElementById("queryRangeOrder").value=queryIndicators[b][3];break}popQueryOperator();if("T"!=document.getElementById("queryIndiType").value){var f=new XMLHttpRequest,a="&PId=NA";booQueryPeriod&&(a="&PId="+document.getElementById("queryPeriod").options[document.getElementById("queryPeriod").selectedIndex].value);f.open("GET","qry.dtRnge?map_id="+map_id+"&Id="+document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value+
"&SId="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value+a,!0);f.send();f.onreadystatechange=function(){if(4==f.readyState&&200==f.status){if("N/A"==f.responseText)alert("No Data Found For Query!!!");else{var a=eval("("+f.responseText+")");document.getElementById("queryDataRange").innerHTML="Data Range : "+a[0][0]+" - "+a[0][1]}document.body.style.cursor="default"}}}}}
function popQueryOperator(){var a=document.createElement("option");a.value="=";a.innerHTML="=";document.getElementById("queryDataOper").appendChild(a);a=document.createElement("option");a.value="<>";a.innerHTML="<>";document.getElementById("queryDataOper").appendChild(a);"T"!=document.getElementById("queryIndiType").value?(a=document.createElement("option"),a.value="<",a.innerHTML="<",document.getElementById("queryDataOper").appendChild(a),a=document.createElement("option"),a.value=">",a.innerHTML=
">",document.getElementById("queryDataOper").appendChild(a),a=document.createElement("option"),a.value="<=",a.innerHTML="<=",document.getElementById("queryDataOper").appendChild(a),a=document.createElement("option"),a.value=">=",a.innerHTML=">="):(a=document.createElement("option"),a.value="L",a.innerHTML="Like");document.getElementById("queryDataOper").appendChild(a)}
function viewQueryIndiSampleData(){document.body.style.cursor="wait";if(""==document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value)alert("No Indicator Selected!!!");else{var a=new XMLHttpRequest,b="&PId=NA";booQueryPeriod&&(b="&PId="+document.getElementById("queryPeriod").options[document.getElementById("queryPeriod").selectedIndex].value);a.open("GET","qry.smpDt?map_id="+map_id+"&Id="+document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value+
"&SId="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value+b,!0);a.send();a.onreadystatechange=function(){if(4==a.readyState&&200==a.status)if("N/A"==a.responseText)document.body.style.cursor="default",alert("No Data Found For Query!!!");else{for(var b=eval("("+a.responseText+")"),c=document.getElementById("indicatorDataSelector").innerHTML="",d=0;d<b.length;d++)c+="<option>"+b[d][0]+"</option>";document.getElementById("indicatorDataSelector").innerHTML=
c;$("#divQueryDataViewer").dialog("open");document.body.style.cursor="default"}}}}function setQueryData(){document.getElementById("queryDataVal").value=document.getElementById("indicatorDataSelector").options[document.getElementById("indicatorDataSelector").selectedIndex].value;$("#divQueryDataViewer").dialog("close")}
function queryMap(){document.body.style.cursor="wait";if(""==document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value)alert("No Indicator Selected!!!");else if(""==document.getElementById("queryDataVal").value)alert("No Value Selected!!!");else{var a="&PId=NA";booQueryPeriod&&(a="&PId="+document.getElementById("queryPeriod").options[document.getElementById("queryPeriod").selectedIndex].value);var a="map_id="+map_id+"&LId="+document.getElementById("queryLayer").options[document.getElementById("queryLayer").selectedIndex].value+
"&IId="+document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value+"&CId="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value+"&OId="+document.getElementById("queryDataOper").options[document.getElementById("queryDataOper").selectedIndex].value+"&VId="+document.getElementById("queryDataVal").value+"&TId="+document.getElementById("queryIndiType").value+a,b=new XMLHttpRequest;b.open("GET",
"qry.do?"+a,!0);b.send();b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){sendEvtReq=!1;if("N/A"==b.responseText)alert("No Data Found For Query!!!");else{var a=eval("("+b.responseText+")");displayQueryData(a);setQueryMarkerData(a)}document.body.style.cursor="default"}}}}
function displayQueryData(a){for(var b="<table border='1'><tr><td>Name</td><td>Value</td></tr>",f=0;f<a.length;f++)b=b+"<tr><td>"+a[f][1]+"</td><td>"+a[f][2]+"</td></tr>";b+="<tr><td colspan='2' style='text-align: center;'><input type='button' value='Export' onclick='exportMapData()'></td></tr></table>";document.getElementById("queryInfoDiv").innerHTML=b;document.getElementById("queryInfoDiv").style.display="block"}
function exportMapData(){var a="&PId=NA";booQueryPeriod&&(a="&PId="+document.getElementById("queryPeriod").options[document.getElementById("queryPeriod").selectedIndex].value);a="LId="+document.getElementById("queryLayer").options[document.getElementById("queryLayer").selectedIndex].value+"&IId="+document.getElementById("queryIndicator").options[document.getElementById("queryIndicator").selectedIndex].value+"&CId="+document.getElementById("queryCategory").options[document.getElementById("queryCategory").selectedIndex].value+
"&OId="+document.getElementById("queryDataOper").options[document.getElementById("queryDataOper").selectedIndex].value+"&VId="+document.getElementById("queryDataVal").value+"&TId="+document.getElementById("queryIndiType").value+a+"&mapId="+map_id+"&mapType="+map_rltd;window.open("query.report?"+a,"_blank")}
function setQueryMarkerData(a){var b="",b="",b=document.getElementById("queryLayer").options[document.getElementById("queryLayer").selectedIndex].value,b=b.substring(b.indexOf("^")+1,b.length);clearHatchedObjects();for(var f=0;f<a.length;f++){var c=a[f];if("PN"==b)for(var d=0;d<markers.length;d++){if(markers[d].id==c[0]){var e=new google.maps.Marker({position:markers[d].position,map:map});markers.push(e);e.type="QryObj"}}else if("OP"==b)for(var e="#FFFF00",k="3",d=0;d<polyLinePathMulti.length;d++){if(polyLinePathMulti[d].id==
c[0]){var m=new google.maps.Polyline({path:polyLinePathMulti[d].path,strokeColor:e,strokeOpacity:1,strokeWeight:k});polyLinePathMulti.push(m);m.type="QryPolyObj";m.setMap(map)}}else if("CP"==b)for(e="#8B0000",k="2",d=0;d<closedPolyMulti.length;d++)closedPolyMulti[d].id==c[0]&&(m=new google.maps.Polygon({path:closedPolyMulti[d].path,strokeOpacity:.8,strokeWeight:k,fillColor:e,fillOpacity:.35}),closedPolyMulti.push(m),m.type="QryPolygonObj",m.setMap(map))}};var arr_layer=[];function zoomExtent(){map.setZoom(parseInt(zoom));map.setCenter({lat:parseFloat(lati),lng:parseFloat(longi)});for(var a=0;a<markers.length;a++)"OthLyr"==markers[a].type&&markers[a].setVisible(!1)}function polygonOptionSet(){for(i=0;i<closedPolyMulti.length;i++)closedPolyMulti[i].setOptions({clickable:!0})}
function divMenu(a){"layer"==a?(polygonOptionSet(),$("li.highlight").removeClass("highlight"),$("#selLyr").parent().addClass("highlight"),document.getElementById("tableLayer").style.display="block",document.getElementById("tableSearch").style.display="none",document.getElementById("tableQuery").style.display="none",document.getElementById("tableBuffer").style.display="none",document.getElementById("tableDistance").style.display="none",document.getElementById("queryInfoDiv").style.display="none",google.maps.event.removeListener(map_clicked_listener)):
"search"==a?(polygonOptionSet(),$("li.highlight").removeClass("highlight"),$("#selSrch").parent().addClass("highlight"),document.getElementById("tableLayer").style.display="none",document.getElementById("tableSearch").style.display="block",document.getElementById("tableQuery").style.display="none",document.getElementById("tableBuffer").style.display="none",document.getElementById("tableDistance").style.display="none",document.getElementById("queryInfoDiv").style.display="none",google.maps.event.removeListener(map_clicked_listener),
popSearchLayers()):"query"==a?(polygonOptionSet(),$("li.highlight").removeClass("highlight"),$("#selQuery").parent().addClass("highlight"),document.getElementById("tableLayer").style.display="none",document.getElementById("tableSearch").style.display="none",document.getElementById("tableQuery").style.display="block",document.getElementById("tableBuffer").style.display="none",document.getElementById("tableDistance").style.display="none",google.maps.event.removeListener(map_clicked_listener),popQueryLayers()):
"distance"==a&&($("li.highlight").removeClass("highlight"),$("#selDist").parent().addClass("highlight"),document.getElementById("tableLayer").style.display="none",document.getElementById("tableSearch").style.display="none",document.getElementById("tableQuery").style.display="none",document.getElementById("tableBuffer").style.display="none",document.getElementById("tableDistance").style.display="block",document.getElementById("queryInfoDiv").style.display="none",getDistance())}
function refreshMap(){clearHatchedObjects()}
function clearHatchedObjects(){resetValue();for(var a=0;a<markers.length;a++)"SrchObj"!=markers[a].type&&"QryObj"!=markers[a].type&&"DisObj"!=markers[a].type||markers[a].setVisible(!1);for(a=0;a<polyLinePathMulti.length;a++)"QryPolyObj"==polyLinePathMulti[a].type&&polyLinePathMulti[a].setVisible(!1);for(a=0;a<closedPolyMulti.length;a++)"QryPolygonObj"!=closedPolyMulti[a].type&&"SrchPolygonObj"!=closedPolyMulti[a].type||closedPolyMulti[a].setVisible(!1);resetValue();removeCircle()};var dist=0,pnt_arr=[],map_clicked_listener=null;function getDistance(){for(i=0;i<closedPolyMulti.length;i++)closedPolyMulti[i].setOptions({clickable:!1});map_clicked_listener=map.addListener("click",function(a){a=new google.maps.Marker({position:a.latLng,icon:"http://74.50.58.66/systems/od_creche/icons/distance.png",map:map});markers.push(a);a.type="DisObj";pnt_arr.push(a.getPosition());1<pnt_arr.length&&calcDistance()})}
function calcDistance(){for(var a="",b=0;b<pnt_arr.length;b++)b==pnt_arr.length-1&&(dist="km"==document.getElementById("distanceUnit").value?parseFloat(dist)+parseFloat(google.maps.geometry.spherical.computeDistanceBetween(pnt_arr[pnt_arr.length-2],pnt_arr[pnt_arr.length-1])/1E3):parseFloat(dist)+parseFloat(google.maps.geometry.spherical.computeDistanceBetween(pnt_arr[pnt_arr.length-2],pnt_arr[pnt_arr.length-1]))),a=new google.maps.Polyline({path:pnt_arr,geodesic:!0,strokeColor:"#0000FF",strokeOpacity:1,
strokeWeight:1});polyLinePathMulti.push(a);a.type="DisPath";a.setMap(map);document.getElementById("distanceViewer").value=parseFloat(dist).toFixed(2)}function resetValue(){document.getElementById("distanceViewer").value="0";document.getElementById("distanceUnit").selectedIndex="0";for(var a=0;a<markers.length;a++)"DisObj"==markers[a].type&&markers[a].setVisible(!1);for(a=0;a<polyLinePathMulti.length;a++)"DisPath"==polyLinePathMulti[a].type&&polyLinePathMulti[a].setVisible(!1);pnt_arr=[];dist=0}
function convertDistance(){var a=null,a=null;"km"==document.getElementById("distanceUnit").value?(a=document.getElementById("distanceViewer").value,a/=1E3,document.getElementById("distanceViewer").value=parseFloat(a).toFixed(2)):"mtr"==document.getElementById("distanceUnit").value&&(a=document.getElementById("distanceViewer").value,a*=1E3,document.getElementById("distanceViewer").value=parseFloat(a).toFixed(2))};var map,map_id=null,map_rltd="",gpMapName=null,lati=null,longi=null,zoom=null,markers=[],polyLinePathMulti=[],closedPolyMulti=[],circleMulti=[];
function initMap(){map_id=document.getElementById("map_id").value;lati=document.getElementById("lati").value;longi=document.getElementById("longi").value;zoom=document.getElementById("zoom").value;map_rltd="21"==map_id?"ST":"DT";map=new google.maps.Map(document.getElementById("map"),{zoom:parseInt(zoom),center:{lat:parseFloat(lati),lng:parseFloat(longi)},mapTypeId:google.maps.MapTypeId.ROADMAP});document.getElementById("selName").innerHTML=document.getElementById("map_name").value;prepLayersTab(map_id)}
;
